# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
#url:              http://bharathgs.github.io/hyde/
baseurl:          http://bharathgs.github.io/hyde/

author:
  name:           'Bharath G.S'
  url:            https://twitter.com/bharathjarvis

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bharathgs/hyde
