# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: false

# Setup
title:             Cognition
tagline:          'No free lunch'
description:      'Data science and Machine learning'
#url:              http://bharathgs.github.io/hyde/
baseurl:           https://bharathgs.github.io/

author:
  name:           'Bharath G.S'
  url:            https://twitter.com/bharathjarvis

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/bharathgs/bharathgs.github.io/
